### PR TITLE
process dependencies in topological order

### PR DESCRIPTION
**Pull request by mikolalysenko**
This should fix https://github.com/stackgl/glslify/issues/44

Note that a few of the test cases break now because they are over constraining the variable renamings.  This is still sort of a first pass at things.  I'd like to make the file names use the path as a hash and then just concatenate all the scripts in one shot.

### CODE REVIEW

**Comment by mikolalysenko** [comment]
CC @hughsk @mattdesl

**Comment by mikolalysenko** [comment]
Wiki: https://en.wikipedia.org/wiki/Topological_sorting

**Comment by hughsk** [comment]
Whoa, this is a wonderful thing to wake up to. I'll take a look soon and fix up the tests, thanks a ton!

**Comment by mattdesl** [comment]
:tada: :clap: Amazing stuff @mikolalysenko !

**Comment by hughsk** [comment]
Yup, this fixes #44! Thanks so much again @mikolalysenko :D

**Comment by hughsk** [comment]
I've found another failing test case that I believe is a result of sorting the deps, _but_ I think it's pretty unlikely to come up in practice — leaving the test case in there in case anybody runs into the issue and wants to tackle it, but right now I don't think it's a big deal :)

**Comment by mattdesl** [comment]
Can you point to test case?

**Comment by hughsk** [comment]
@mattdesl in [this shader](https://github.com/stackgl/glslify-bundle/blob/b49d1eb4fc5b3dba1e84f6a78a4af4259660f3f8/fixtures/complex.glsl#L3-L8), `RayResult` and `Ray` are included as part of `march` instead of the main file and as such are loaded later than required. Test script is [here](https://github.com/stackgl/glslify-bundle/blob/b49d1eb4fc5b3dba1e84f6a78a4af4259660f3f8/test/complex-valid-shader.js) :)

**Pull request merged**
